language: objective-c
script:
- set -o pipefail
- travis_retry xcodebuild -workspace RolePlayingCore.xcworkspace -scheme "RolePlayingCore" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test
